apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow-serving
spec:
  name: test-model
  predictors:
    - graph:
        children: []
        implementation: MLFLOW_SERVER
        modelUri: s3://artifacts/24/0cce287702c547578f9d8054994bd739/artifacts/artifacts
        envSecretRefName: bpk-seldon-init-container-secret
        name: regressor
      name: default
      replicas: 1
