apiVersion: v1
kind: Secret
metadata:
  name: bpk-seldon-init-container-secret
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: s3
  RCLONE_CONFIG_S3_PROVIDER: minio
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: admin
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: dYzac5sD8R
  RCLONE_CONFIG_S3_ENDPOINT: http://mlflow-minio.mlops.svc.cluster.local:9000
  RCLONE_CONFIG_S3_ENV_AUTH: "false"
